### PR TITLE
Custom handlebar helpers

### PR DESCRIPTION
**Pull request by guided1**
Adding ability to add custom handlebars helpers from the project.

### CODE REVIEW

**Comment by guided1** [comment]
Is this ok? I branched from develop... was I supposed to branch from master?

**Comment by fmvilas** [comment]
Hi @guided1. Sorry for the late response. It looks good to me.

I changed the PR to point to develop because I'm following [Git flow](https://danielkummer.github.io/git-flow-cheatsheet/).

Thanks for your time, really appreciate.

**Comment by guided1** [comment]
Ugh... forgot to update the documentation in README.md

**Comment by fmvilas** [comment]
You're right. Would you mind to open a PR with the missing documentation? I'll be very thankful 🙏

**Comment by guided1** [comment]
Sure no problem. Just away at the moment. Will do it in a few days.

**Comment by fmvilas** [comment]
Thanks! Enjoy!

**Pull request merged**
